### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by philippe-richard** [irisbaron/vsam-express-demo#5]
i tried to follow your demo and run into an issue when running the 'npm install' command.
I have the latest version of nodejs installed v6.11.2   and npm 3.10.10  .
i have cloned your package. 
When i run the npm install command i get:
-[37;40mnpm-[0m -[0m-[31;40mERR!-[0m-[35m-[0m vsam.js@2.0.0 install: `node-gyp r
ebuild`                                                                         
-[0m-[37;40mnpm-[0m -[0m-[31;40mERR!-[0m-[35m-[0m Exit status 1                 
-[0m-[37;40mnpm-[0m -[0m-[31;40mERR!-[0m-[35m-[0m                               
-[0m-[37;40mnpm-[0m -[0m-[31;40mERR!-[0m-[35m-[0m Failed at the vsam.js@2.0.0 in
stall script 'node-gyp rebuild'.                                                
-[0m-[37;40mnpm-[0m -[0m-[31;40mERR!-[0m-[35m-[0m Make sure you have the latest 
version of node.js and npm installed.                                           
-[0m-[37;40mnpm-[0m -[0m-[31;40mERR!-[0m-[35m-[0m If you do, this is most likely
 a problem with the vsam.js package,                                            
-[0m-[37;40mnpm-[0m -[0m-[31;40mERR!-[0m-[35m-[0m not with npm itself.          
-[0m-[37;40mnpm-[0m -[0m-[31;40mERR!-[0m-[35m-[0m Tell the author that this fail
s on your system:                                                               
-[0m-[37;40mnpm-[0m -[0m-[31;40mERR!-[0m-[35m-[0m     node-gyp rebuild          
-[0m-[37;40mnpm-[0m -[0m-[31;40mERR!-[0m-[35m-[0m You can get information on how
 to open an issue for this project with:                                        
-[0m-[37;40mnpm-[0m -[0m-[31;40mERR!-[0m-[35m-[0m     npm bugs vsam.js          
-[0m-[37;40mnpm-[0m -[0m-[31;40mERR!-[0m-[35m-[0m Or if that isn't available, yo
u can get their info via:                                                       
-[0m-[37;40mnpm-[0m -[0m-[31;40mERR!-[0m-[35m-[0m     npm owner ls vsam.js      
-[0m-[37;40mnpm-[0m -[0m-[31;40mERR!-[0m-[35m-[0m There is likely additional log
ging output above.                                                              
-[0m                                                                            
-[37;40mnpm-[0m -[0m-[31;40mERR!-[0m-[35m-[0m Please include the following file 
with any support request:                                                       
-[0m-[37;40mnpm-[0m -[0m-[31;40mERR!-[0m-[35m-[0m     /u/prichar/github/vsam-exp
ress-demo/npm-debug.log  
                                                       
file npm-debug.log contains the following:
0 info it worked if it ends with ok                                             
1 verbose cli [ '/Z23R01/usr/lpp/IBM/cnj/IBM/node-v6.11.2-os390-s390x/bin/node',
1 verbose cli   '/usr/lpp/IBM/cnj/IBM/node-latest-os390-s390x/bin/npm',         
1 verbose cli   'install' ]                                                     
2 info using npm@3.10.10                                                        
3 info using node@v6.11.2                                                       
4 silly loadCurrentTree Starting                                                
5 silly install loadCurrentTree                                                 
6 silly install readLocalPackageData                                            
7 silly install normalizeTree                                                   
8 silly loadCurrentTree Finishing                                               
9 silly loadIdealTree Starting                                                  
10 silly install loadIdealTree                                                  
11 silly cloneCurrentTree Starting                                              
12 silly install cloneCurrentTreeToIdealTree                                    
13 silly cloneCurrentTree Finishing                                             
14 silly loadShrinkwrap Starting                                                
15 silly install loadShrinkwrap                                                 
16 silly loadShrinkwrap Finishing                                               
17 silly loadAllDepsIntoIdealTree Starting                                      
18 silly install loadAllDepsIntoIdealTree                                       
19 silly fetchNamedPackageData vsam.js                                          
20 silly mapToRegistry name vsam.js                                             
21 silly mapToRegistry using default registry                                   
23 silly mapToRegistry data Result {                                            
23 silly mapToRegistry   raw: 'vsam.js',                                        
23 silly mapToRegistry   scope: null,                                           
23 silly mapToRegistry   escapedName: 'vsam.js',                                
23 silly mapToRegistry   name: 'vsam.js',                                       
23 silly mapToRegistry   rawSpec: '',                                           
23 silly mapToRegistry   spec: 'latest',                                        
23 silly mapToRegistry   type: 'tag' }                                          
24 silly mapToRegistry uri https://registry.npmjs.org/vsam.js                   
25 verbose request uri https://registry.npmjs.org/vsam.js                       
26 verbose request no auth needed                                               
27 info attempt registry request try #1 at 10:43:48 GMT+0100 ()                 
28 verbose request id f1d7fc96b84fd681                                          
29 verbose etag W/"9a3a70fcae768bd1d329fd0aa3a3c4c4"                            
30 verbose lastModified Wed, 01 Aug 2018 16:02:43 GMT                           
31 http request GET https://registry.npmjs.org/vsam.js                          
32 http 304 https://registry.npmjs.org/vsam.js                                  
33 verbose headers { date: 'Fri, 28 Sep 2018 09:46:33 GMT',                     
33 verbose headers   connection: 'keep-alive',                                  
33 verbose headers   'set-cookie': [ '__cfduid=d642917b6fc9f3d3a7f271fa63730d155
33 verbose headers   'cf-cache-status': 'HIT',                                  
33 verbose headers   'cache-control': 'max-age=300',                            
33 verbose headers   'cf-ray': '461548968831c2b5-FRA',                          
33 verbose headers   etag: '"9a3a70fcae768bd1d329fd0aa3a3c4c4"',                
...
...
35 verbose etag https://registry.npmjs.org/vsam.js from cache                   
36 verbose get saving vsam.js to /u/prichar/.npm/registry.npmjs.org/vsam.js/.cac
37 verbose correctMkdir /u/prichar/.npm correctMkdir not in flight; initializing
38 silly resolveWithNewModule vsam.js@2.0.0 checking installable status         
39 silly cache add args [ 'vsam.js@2.0.0', null ]                               
40 verbose cache add spec vsam.js@2.0.0                                         
41 silly cache add parsed spec Result {                                         
41 silly cache add   raw: 'vsam.js@2.0.0',                                      
41 silly cache add   scope: null,                                               
41 silly cache add   escapedName: 'vsam.js',                                    
41 silly cache add   name: 'vsam.js',                                           
41 silly cache add   rawSpec: '2.0.0',                                          
41 silly cache add   spec: '2.0.0',                                             
41 silly cache add   type: 'version' }                                          
42 silly addNamed vsam.js@2.0.0                                                 
43 verbose addNamed "2.0.0" is a plain semver version for vsam.js               
44 silly mapToRegistry name vsam.js                                             
45 silly mapToRegistry using default registry                                   
46 silly mapToRegistry registry https://registry.npmjs.org/                     
47 silly mapToRegistry data Result {                                            
47 silly mapToRegistry   raw: 'vsam.js',                                        
47 silly mapToRegistry   scope: null,                                           
47 silly mapToRegistry   escapedName: 'vsam.js',                                
47 silly mapToRegistry   name: 'vsam.js',                                       
47 silly mapToRegistry   rawSpec: '',                                           
...
...
silly lifecycle inflight@1.0.6~install: no script for install, continuing  
silly install glob@7.1.3 /u/prichar/github/vsam-express-demo/node_modules/.
info lifecycle glob@7.1.3~install: glob@7.1.3                              
silly lifecycle glob@7.1.3~install: no script for install, continuing      
silly install rimraf@2.6.2 /u/prichar/github/vsam-express-demo/node_modules
info lifecycle rimraf@2.6.2~install: rimraf@2.6.2                          
silly lifecycle rimraf@2.6.2~install: no script for install, continuing    
silly install fstream@1.0.11 /u/prichar/github/vsam-express-demo/node_modul
info lifecycle fstream@1.0.11~install: fstream@1.0.11                      
silly lifecycle fstream@1.0.11~install: no script for install, continuing  
silly install tar@2.2.1 /u/prichar/github/vsam-express-demo/node_modules/.s
info lifecycle tar@2.2.1~install: tar@2.2.1                                
silly lifecycle tar@2.2.1~install: no script for install, continuing       
silly install node-gyp@3.8.0 /u/prichar/github/vsam-express-demo/node_modul
info lifecycle node-gyp@3.8.0~install: node-gyp@3.8.0                      
silly lifecycle node-gyp@3.8.0~install: no script for install, continuing  
silly install vsam.js@2.0.0 /u/prichar/github/vsam-express-demo/node_module
info lifecycle vsam.js@2.0.0~install: vsam.js@2.0.0                        
verbose lifecycle vsam.js@2.0.0~install: unsafe-perm in lifecycle false    
verbose lifecycle vsam.js@2.0.0~install: PATH: /$VERSION/usr/lpp/IBM/cnj/IB
verbose lifecycle vsam.js@2.0.0~install: CWD: /u/prichar/github/vsam-expres
silly lifecycle vsam.js@2.0.0~install: Args: [ '-c', 'node-gyp rebuild' ]  
silly lifecycle vsam.js@2.0.0~install: Returned: code: 1  signal: null     
info lifecycle vsam.js@2.0.0~install: Failed to exec install script        
verbose unlock done using /u/prichar/.npm/_locks/staging-487548537074eccf.l
silly rollbackFailedOptional Starting                                      
silly rollbackFailedOptional Finishing                                     
silly runTopLevelLifecycles Finishing                                      
silly install printInstalled                                               
warn vsamdemo@1.0.0 No repository field.                                   
verbose If you need help, you may report this error at:                    
verbose     <https://github.com/npm/npm/issues>                            
verbose stack Error: vsam.js@2.0.0 install: `node-gyp rebuild`             
verbose stack Exit status 1                                                
verbose stack     at EventEmitter.<anonymous> (/$VERSION/usr/lpp/IBM/cnj/IB
verbose stack     at emitTwo (events.js:106:13)                            
verbose stack     at EventEmitter.emit (events.js:191:7)                   
verbose stack     at ChildProcess.<anonymous> (/$VERSION/usr/lpp/IBM/cnj/IB
verbose stack     at emitTwo (events.js:106:13)                            
verbose stack     at ChildProcess.emit (events.js:191:7)                   
verbose stack     at maybeClose (internal/child_process.js:902:16)         
verbose stack     at Process.ChildProcess._handle.onexit (internal/child_pr
verbose pkgid vsam.js@2.0.0                                                
verbose cwd /u/prichar/github/vsam-express-demo                            
error OS/390 26.00                                                         
error argv "/Z23R01/usr/lpp/IBM/cnj/IBM/node-v6.11.2-os390-s390x/bin/node" 
error node v6.11.2                                                         
error npm  v3.10.10                                                        
error code ELIFECYCLE                                                      
error vsam.js@2.0.0 install: `node-gyp rebuild`                            
error Exit status 1                                                        
error Failed at the vsam.js@2.0.0 install script 'node-gyp rebuild'.       
error Make sure you have the latest version of node.js and npm installed.  
error If you do, this is most likely a problem with the vsam.js package,   
error not with npm itself.                                                 
error Tell the author that this fails on your system:                      
error     node-gyp rebuild                                                 
error You can get information on how to open an issue for this project with
error     npm bugs vsam.js                                                 
error Or if that isn't available, you can get their info via:              
error     npm owner ls vsam.js                                             
error There is likely additional logging output above.                     
verbose exit [ 1, true ]                                                   

Would you have any idea ?

**Comment by philippe-richard** [comment]
pb solved, see https://www.ibm.com/developerworks/community/forums/html/topic?id=b2a77068-9a2e-498a-881e-e5dd9e23e9aa&ps=25

**Comment by philippe-richard** [comment]
pb solved, see https://www.ibm.com/developerworks/community/forums/html/topic?id=b2a77068-9a2e-498a-881e-e5dd9e23e9aa&ps=25
